# Generated by Django 5.2.1 on 2025-06-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='Add_item/')),
            ],
        ),
    ]
