# Generated by Django 5.2.1 on 2025-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_item',
            name='id',
        ),
        migrations.AlterField(
            model_name='add_item',
            name='item_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
