# Generated by Django 5.2.1 on 2025-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_add_item_id_alter_add_item_item_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_item',
            name='item_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
