# Generated by Django 5.2.1 on 2025-07-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_add_item_item_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('Account_holder', models.CharField(max_length=100)),
                ('Account_Number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
