# Generated by Django 5.2.1 on 2025-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rename_account_number_orderview_account_number_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
