services:
  - type: web
    name: food-order
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn food_order.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-(9l9ec8c&*!hznzjn*)wmmc3^h!+-x6+@9cssxd6v%p+z^v7^5
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
    postDeploy: |
      python manage.py migrate
      python manage.py collectstatic --noinput
